### ISSUE TITLE
Monitor Controller/Widget til at vise værdi af en variabel

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/pyagents#1]
Netlogo kan man udover grafen der viser en variabel over tid, også bare få vist den nuværende værdi af en variabel. Det de kalder en "Monitor", kan være det også kunne være brugbart for os.

**Comment by JensKanstrupLarsen** [comment]
Monitors er nu færdige, et eksempel kan ses i `epidemic.py`.

**Comment by dybber** [comment]
Cool. Jeg tænker om monitors måske skal placeres ovre i højre side sammen med graferne, eller hvad tænker du? Så har man alt output derovre.

Det er selvfølgelig lidt mere bøvlet kodemæssigt. Det er ikke så vigtigt, vi kan vente med at tage det til når gymnasielærerne har leget med det og givet input til hvordan det hele skal virke.
