### ISSUE TITLE
Gør agenters retning tydligt i udseendet

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/pyagents#12]
I NetLogo er en agent som standard en pil med retning (eller en "turtle" i Logo/Python's turtle bibliotek). Lad os evt. bruge cirka samme udseende som vores standard agent. 

Evt. kan vi også som NetLogo, give agenter en tilfældig farve som standard, så hvis man laver de helt simple modeller, så kan man se forskel på dem der er tilføjet.

**Comment by JensKanstrupLarsen** [comment]
Det er nu muligt at vise agenternes retning ved at sætte modellens `show_direction = True`.

**Comment by dybber** [comment]
Ser fint ud!
