### ISSUE TITLE
Kombiner epidemimodel og bytteøkonomi-model

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/pyagents#15]
Efter vi har en simpel model for bytteøkonomi (issue #14), så kan vi evt. prøve at kombinere det med epidemimodellen.

Fra Christian Langholz Carstensen:
> "hvis man skal gå videre med ideen om at implementere noget økonomisk i den epidemiske model I skrevet, så er en mulighed at give agenterne nogle varer, som de gerne vil handle med hinanden, fordi de har forskellige præferencer for dem (det er mikro 101). Men social distancing hindrer en del af handlerne, så økonomien svækkes og BNP falder, hvilket er effekten er krisen. Kravene til social distancering viser således et trade-off mellem økonomisk aktivitet og bekæmpelse af epidemien."

**Comment by JensKanstrupLarsen** [comment]
Første eksempel i form af `bnb_pandemic.py` er oppe nu.

**Comment by JensKanstrupLarsen** [comment]
Modellen virker nu, men er ikke særlig interessant fra et økonomisk perspektiv. Der skal nok tilføjes flere parametre, men jeg er usikker på hvad.

**Comment by dybber** [comment]
Fint nok. Det er også denne del som vi skal have gymnasielærerne til at lave faktisk, men nu ved vi at en primitiv udgave kan lade sig gøre.

Lidt kommentarer til koden:
 - brug hellere math.sqrt() end **0.5, det gør koden mere læselig
 - ville være rart med lidt flere kommentarer i step-funktionen, evt. hvis den kunne opdeles og bruge nogle underfunktioner, vil det også gøre det mere læseligt
 - update_visual, kunne måske i stedet hedde "size_from_utility" eller lign.
