### ISSUE TITLE
Checkbox der styrer boolean

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/pyagents#16]
Tilføj en ny "checkbox" widget, som man kan tilføje til en model, der er koblet på en boolean variabel.

Motivationen er at man kan bruge checkboxen til at styre om en feature i modellen skal slås til eller fra (fx slå social distancering til/fra i epidemimodellen)

**Comment by JensKanstrupLarsen** [comment]
Checkbox er tilføjet, eksempel kan ses i `bnb_pandemic.py`.

**Comment by dybber** [comment]
Ser fint ud.
