### ISSUE TITLE
Slider med label og indikator af nuværende værdi

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/pyagents#2]
Slideren skal udvides til at vise navnet på den variabel den styrer, og vise den nuværende værdi. Det kan fx gøres ved at sætte et label over til variabelnavnet og en QSpinBox ved siden af til at vise værdien.

Her står der lidt om hvordan man laver composite widgets, ved at sætte flere komponenter sammen til et: https://forum.qt.io/topic/86661/designing-a-composite-widget

**Comment by JensKanstrupLarsen** [comment]
Sliders viser nu variabelnavn og nuværende værdi... men det kunne måske være pænere.

**Comment by dybber** [comment]
Det er helt fint til en start
