### ISSUE TITLE
Simpel standard model, og mulighed for mere avanceret

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/pyagents#6]
Jeg foreslår at vores standard model, når man skriver `modello = Model(50, 50)`, altid skal angives en setup og step-funktion `Model(50, 50, setup, step)` så alle simple modeller har samme udseende og funktionalitet. 

Når elever har fået erfaring kan de lære selv at tilføje flere komponenter.

Når de har fået endnu mere erfaring, eller for ekspert-brugere, kan de i stedet tage udgangspunkt i en `BaseModel(50, 50)` og derfra tilføje de komponenter der er nødvendige

**Comment by JensKanstrupLarsen** [comment]
Der er nu tilføjet muligheden for at lave en simplere model, kaldet `SimpleModel`, som tager `setup` og `step` funktionen i dennes konstruktor.
