### ISSUE TITLE
Beslutning: PyQtCharts vs. matplotlib til plots

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/pyagents#7]
**Fordele ved PyQtChart:**
PyQtChart integrerer bedre med PyQt5 end matplotlib, samtidig er PyQtChart også det de bruger i Mu-editor, hvis vi vil integrere med den er det måske bedre at bruge samme?

**Fordele ved Matplotlib:** Matplotlib er vist mere "standard" i Python verden, dvs. mange flere tutorials, guides, documentation end PyQtChart. Hvis vi vil gøre det muligt på et tidspunkt at lade brugerne customize deres egne plots, er det måske bedre at elever lærer at bruge matplotlib end PyQtChart?

Mit bud: Jeg tænker det er meget begrænset brug vi har af grafer her i starten, og så er det bedre med noget der integrerer godt (PyQtChart), og hvis vi så vil udvide plotting-mulighederne senere, så behøver det nok ikke kræve alverden at skifte over til matplotlib på det tidspunkt.

**Comment by JensKanstrupLarsen** [comment]
Jeg har tilføjet et PyQt-plot alternativ nu; ud over at integrere nemmere lader det også til at være bedre optimeret.

**Comment by dybber** [comment]
Hvordan kan det være du endte med PyQtGraph og ikke PyQtChart? PyQtChart er den der følger med "Mu editoren", hvis vi vil bruge den, vil det være smartere, da man så ikke skal installere nogle afhængigheder

**Comment by dybber** [comment]
Husk også at fjerne imports til matplotlib, når vi ikke længere bruger det: https://github.com/DatalogiForAlle/pyagents/blob/cf29b5346957954fae8ec337aac4d75bd00e8503/agents/ui.py#L8

**Comment by JensKanstrupLarsen** [comment]
Nå ja, jeg må have læst forkert. Jeg har prøvet at skifte det til PyQtChart, men der lader til at være nogle issues med højden af graf-widget'en.
