### ISSUE TITLE
Mulighed for at slå opdatering af SimulationArea fra

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/pyagents#8]
I NetLogo kan man slå opdateringen af displayet fra, for at få simuleringen til at køre hurtigere. Det kunne vi også overveje. Pt. kører vores simulering med en opdateringshastighed på 60fps, så først skal vi nok gøre det muligt generelt at ændre opdateringshastigheden.

**Comment by JensKanstrupLarsen** [comment]
Det er nu muligt at slå opdatering af simulation-area fra med en knap (det gør dog ikke så meget, da graferne er det, der tager mest tid at rendere, især når der er mange datapunkter).

**Comment by dybber** [comment]
Fint at det virker, men jeg er ikke så vild med knappen og dens placering. Vi kan lige snakke om hvordan vi ellers kan gøre det, så det ikke er en knap der fylder så meget i user-interfacet. Måske kunne man gøre det til en del af SimulationArea "widgetten" på en måde. 

Vi må se på hvordan vi kan optimere det med graferne på et senere tidspunkt.
